### ISSUE TITLE
Can't convert 'NoneType' object to str implicitly - when using nginx

### ISSUE THREAD

**Issue by mrcartier** [braintree/braintree_flask_example#23]
### General information

* Environment: Sandbox
* Language, language version, and OS: Python 3.5.2 in venv on Ubuntu 16.04 LTS

### Issue description

It runs just fine when following the setup instructions. However when trying to run it behind nginx I get the following output

    [2019-02-07 18:53:07 -0500] [8877] [INFO] Starting gunicorn 19.4.5
    [2019-02-07 18:53:07 -0500] [8877] [INFO] Listening at: http://127.0.0.1:8000 (8877)
    [2019-02-07 18:53:07 -0500] [8877] [INFO] Using worker: sync
    [2019-02-07 18:53:07 -0500] [8880] [INFO] Booting worker with pid: 8880
    [2019-02-07 18:53:15,486] ERROR in app: Exception on /checkouts/new [GET]
    Traceback (most recent call last):
    File "/home/cartier/Documents/braintree_flask/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
    File "/home/cartier/Documents/braintree_flask/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/home/cartier/Documents/braintree_flask/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/home/cartier/Documents/braintree_flask/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
    File "/home/cartier/Documents/braintree_flask/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
    File "/home/cartier/Documents/braintree_flask/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/home/cartier/Documents/braintree_flask/app.py", line 32, in new_checkout
    client_token = generate_client_token()
    File "/home/cartier/Documents/braintree_flask/gateway/__init__.py", line 15, in generate_client_token
    return gateway.client_token.generate()
    File "/home/cartier/Documents/braintree_flask/lib/python3.5/site-packages/braintree/client_token_gateway.py", line 24, in generate
    response = self.config.http().post(self.config.base_merchant_path() + "/client_token", params)
    File "/home/cartier/Documents/braintree_flask/lib/python3.5/site-packages/braintree/configuration.py", line 113, in base_merchant_path
    return "/merchants/" + self.merchant_id
    TypeError: Can't convert 'NoneType' object to str implicitly

I've configured nginx with the following flask settings

    server {
        location / {

		proxy_pass http://127.0.0.1:8000;		
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	    }
    }

Originally I got this error in another flask app so initially I thought I'd just forgot to include or import something. In the other app it's the same behavior; it works without nginx but fails with nginx. So I came back to this standalone braintree_flask app & found the same issue. Any ideas???

**Comment by crookedneighbor** [comment]
I assume you aren't passing your api keys as env variables correctly, given that the stacktrace points out braintree/configuration.py. No merchant id is being passed, so it can't be used to construct the url.

**Comment by Arsur** [comment]
I also had a lot of problems with that. I'am getting my vars from an external config.py depending which environment my app is running on. Even directly writing it in the code did not work. Due to the fact that this error message is not clear, the parsing should be reviewed. At least the error messages.

I would wish there is an error thrown, the environment variable is not existing or not correct formatted. My Error message was TypeError: Can't convert 'str object to str which was very confusing.

took me a lot of time do debug this behavior. And its not the result i want to have, because i still want to add those vars in my config.py but dont know how to get this done.

**Comment by crookedneighbor** [comment]
@Arsur I agree that the error message could be clearer. Feel free to open up a pull request
