### ISSUE TITLE
ImportError: cannot import name 'escape' from 'jinja2'

### ISSUE THREAD

**Issue by PascalSchimmler** [braintree/braintree_flask_example#30]
### General information

* Environment: Sandbox
* Language, language version, and OS: Heroku Deployment, Windows 10

### Issue description

Run the App from heroku cli from Windows 10 

C:\Users\Pascal>heroku logs --tail -a testrainree
 »   Warning: heroku update available from 7.53.0 to 7.60.2.
2022-05-29T08:35:57.663943+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-05-29T08:35:57.663943+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-05-29T08:35:57.663944+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-05-29T08:35:57.663944+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked2022-05-29T08:35:57.663945+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-05-29T08:35:57.663945+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-05-29T08:35:57.663945+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-05-29T08:35:57.663946+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2022-05-29T08:35:57.663946+00:00 app[web.1]: from flask import Flask, redirect, url_for, render_template, request, flash2022-05-29T08:35:57.663947+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
2022-05-29T08:35:57.663947+00:00 app[web.1]: from jinja2 import escape
2022-05-29T08:35:57.663947+00:00 app[web.1]: ImportError: cannot import name 'escape' from 'jinja2' (/app/.heroku/python/lib/python3.10/site-packages/jinja2/__init__.py)
2022-05-29T08:35:57.664146+00:00 app[web.1]: [2022-05-29 08:35:57 +0000] [9] [INFO] Worker exiting (pid: 9)
2022-05-29T08:35:57.674872+00:00 app[web.1]: [2022-05-29 08:35:57 +0000] [10] [ERROR] Exception in worker process
2022-05-29T08:35:57.674874+00:00 app[web.1]: Traceback (most recent call last):
2022-05-29T08:35:57.674874+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2022-05-29T08:35:57.674875+00:00 app[web.1]: worker.init_process()
2022-05-29T08:35:57.674875+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 119, in init_process
2022-05-29T08:35:57.674876+00:00 app[web.1]: self.load_wsgi()
2022-05-29T08:35:57.674876+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2022-05-29T08:35:57.674876+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-05-29T08:35:57.674877+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-05-29T08:35:57.674877+00:00 app[web.1]: self.callable = self.load()
2022-05-29T08:35:57.674877+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2022-05-29T08:35:57.674878+00:00 app[web.1]: return self.load_wsgiapp()
2022-05-29T08:35:57.674878+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2022-05-29T08:35:57.674878+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-05-29T08:35:57.674879+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/util.py", line 358, in import_app
2022-05-29T08:35:57.674879+00:00 app[web.1]: mod = importlib.import_module(module)
2022-05-29T08:35:57.674880+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-05-29T08:35:57.674880+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-05-29T08:35:57.674881+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-05-29T08:35:57.674881+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-05-29T08:35:57.674882+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked2022-05-29T08:35:57.674882+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-05-29T08:35:57.674882+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-05-29T08:35:57.674883+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-05-29T08:35:57.674883+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2022-05-29T08:35:57.674884+00:00 app[web.1]: from flask import Flask, redirect, url_for, render_template, request, flash2022-05-29T08:35:57.674884+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
2022-05-29T08:35:57.674884+00:00 app[web.1]: from jinja2 import escape
2022-05-29T08:35:57.674885+00:00 app[web.1]: ImportError: cannot import name 'escape' from 'jinja2' (/app/.heroku/python/lib/python3.10/site-packages/jinja2/__init__.py)
2022-05-29T08:35:57.675060+00:00 app[web.1]: [2022-05-29 08:35:57 +0000] [10] [INFO] Worker exiting (pid: 10)
2022-05-29T08:35:57.834025+00:00 app[web.1]: [2022-05-29 08:35:57 +0000] [4] [INFO] Shutting down: Master
2022-05-29T08:35:57.834541+00:00 app[web.1]: [2022-05-29 08:35:57 +0000] [4] [INFO] Reason: Worker failed to boot.
2022-05-29T08:35:58.037349+00:00 heroku[web.1]: Process exited with status 3
2022-05-29T08:35:58.099924+00:00 heroku[web.1]: State changed from starting to crashed
2022-05-29T08:35:58.103171+00:00 heroku[web.1]: State changed from crashed to starting
2022-05-29T08:36:00.000000+00:00 app[api]: Build succeeded
2022-05-29T08:36:01.329487+00:00 heroku[web.1]: Starting process with command `gunicorn app:app --log-file -`
2022-05-29T08:36:02.649146+00:00 app[web.1]: [2022-05-29 08:36:02 +0000] [4] [INFO] Starting gunicorn 20.0.4
2022-05-29T08:36:02.649498+00:00 app[web.1]: [2022-05-29 08:36:02 +0000] [4] [INFO] Listening at: http://0.0.0.0:29565 (4)
2022-05-29T08:36:02.649531+00:00 app[web.1]: [2022-05-29 08:36:02 +0000] [4] [INFO] Using worker: sync
2022-05-29T08:36:02.653018+00:00 app[web.1]: [2022-05-29 08:36:02 +0000] [9] [INFO] Booting worker with pid: 9
2022-05-29T08:36:02.682768+00:00 app[web.1]: [2022-05-29 08:36:02 +0000] [9] [ERROR] Exception in worker process
2022-05-29T08:36:02.682769+00:00 app[web.1]: Traceback (most recent call last):
2022-05-29T08:36:02.682780+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2022-05-29T08:36:02.682780+00:00 app[web.1]: worker.init_process()
2022-05-29T08:36:02.682780+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 119, in init_process
2022-05-29T08:36:02.682781+00:00 app[web.1]: self.load_wsgi()
2022-05-29T08:36:02.682781+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
2022-05-29T08:36:02.682781+00:00 app[web.1]: self.wsgi = self.app.wsgi()
2022-05-29T08:36:02.682781+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
2022-05-29T08:36:02.682782+00:00 app[web.1]: self.callable = self.load()
2022-05-29T08:36:02.682782+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
2022-05-29T08:36:02.682782+00:00 app[web.1]: return self.load_wsgiapp()
2022-05-29T08:36:02.682782+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
2022-05-29T08:36:02.682782+00:00 app[web.1]: return util.import_app(self.app_uri)
2022-05-29T08:36:02.682783+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/gunicorn/util.py", line 358, in import_app
2022-05-29T08:36:02.682783+00:00 app[web.1]: mod = importlib.import_module(module)
2022-05-29T08:36:02.682786+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
2022-05-29T08:36:02.682786+00:00 app[web.1]: return _bootstrap._gcd_import(name[level:], package, level)
2022-05-29T08:36:02.682786+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2022-05-29T08:36:02.682787+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2022-05-29T08:36:02.682787+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked2022-05-29T08:36:02.682787+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2022-05-29T08:36:02.682787+00:00 app[web.1]: File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2022-05-29T08:36:02.682788+00:00 app[web.1]: File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2022-05-29T08:36:02.682788+00:00 app[web.1]: File "/app/app.py", line 1, in <module>
2022-05-29T08:36:02.682788+00:00 app[web.1]: from flask import Flask, redirect, url_for, render_template, request, flash2022-05-29T08:36:02.682788+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.10/site-packages/flask/__init__.py", line 14, in <module>
2022-05-29T08:36:02.682789+00:00 app[web.1]: from jinja2 import escape
2022-05-29T08:36:02.682792+00:00 app[web.1]: ImportError: cannot import name 'escape' from 'jinja2' (/app/.heroku/python/lib/python3.10/site-packages/jinja2/__init__.py)
2022-05-29T08:36:02.682857+00:00 app[web.1]: [2022-05-29 08:36:02 +0000] [9] [INFO] Worker exiting (pid: 9)
2022-05-29T08:36:02.714150+00:00 app[web.1]: [2022-05-29 08:36:02 +0000] [4] [INFO] Shutting down: Master
2022-05-29T08:36:02.714177+00:00 app[web.1]: [2022-05-29 08:36:02 +0000] [4] [INFO] Reason: Worker failed to boot.
2022-05-29T08:36:02.859250+00:00 heroku[web.1]: Process exited with status 3
2022-05-29T08:36:02.953722+00:00 heroku[web.1]: State changed from starting to crashed
2022-05-29T08:36:09.657092+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testrainree.herokuapp.com request_id=fa51f27f-67df-4268-b955-ab9a39632656 fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T08:36:10.087238+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testrainree.herokuapp.com request_id=2576853f-e0fe-41f9-b26a-c6f51bebf804 fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T08:40:14.487267+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testrainree.herokuapp.com request_id=a626f7c9-18a6-48ef-8637-ebe67810c84f fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T08:40:14.785163+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testrainree.herokuapp.com request_id=77d2a02d-6952-44bc-9a1f-8292e973e90f fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T08:41:33.930199+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testrainree.herokuapp.com request_id=3731328f-ea49-4d43-a740-09a413d318d0 fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T08:41:34.360119+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testrainree.herokuapp.com request_id=6d1a3875-138f-4a06-9892-617c42504ffb fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T08:59:56.262993+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testrainree.herokuapp.com request_id=72cdcb0f-b2e8-4638-a92a-0662e4284679 fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T08:59:56.529518+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testrainree.herokuapp.com request_id=8e6b9661-d94d-4b10-a021-bfc87535f24c fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T09:06:56.015404+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testrainree.herokuapp.com request_id=90457398-fbc3-4f92-ad7e-0bcc8a064457 fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T09:06:56.295779+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testrainree.herokuapp.com request_id=a599f062-5448-4139-8dd3-c163f1742009 fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T09:14:19.069757+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=testrainree.herokuapp.com request_id=0cc4ea52-5042-45bf-a773-0fade4cec3cf fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https
2022-05-29T09:14:19.850844+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=testrainree.herokuapp.com request_id=32189bfb-1c1f-4d4f-8c33-6ea876a01cc2 fwd="62.216.204.45" dyno= connect= service= status=503 bytes= protocol=https

**Comment by hollabaq86** [comment]
👋  @PascalSchimmler looks like we need to update the example repo to [Flask 2](https://stackoverflow.com/a/71735103).

I don't have an ETA on when we'll get around to updating (fortunately we have a community PR #29 to do this). In the meantime, if you opt to use the branch on #29 this should get around this import error.

**Comment by saralvasquez** [comment]
PR [#29](https://github.com/braintree/braintree_flask_example/pull/29) just got merged, so main should no longer throw this error. I'm going to close this, but please open another issue if you still notice the problem.
